name: Backend
on:
  workflow_dispatch:
jobs:
  build: 
    name: Build all three docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Run test scripts
        run: |
          cd backend
          mvn -DskipTests=true  package

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }} 
          username: sagarzemosolabs
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sagarzemosolabs/greencommute-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/sagarzemosolabs/greencommute-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "MYSQL_URL =${{ secrets.MYSQL_URL }}"
            "MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}"
            "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}"

