name: Build
on:
  push:
    branches:
      - master
jobs:
  build: 
    name: Build all three docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Run test scripts
        run: |
          cd frontend
          npm install
          npm test -- --watchAll=false

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }} 
          username: sagarzemosolabs
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_frontend
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sagarzemosolabs/greencommute-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: frontend/
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }},ghcr.io/sagarzemosolabs/greencommute-frontend:latest
          labels: ${{ steps.meta_frontend.outputs.labels }}

