name: Build
on:
  workflow_dispatch:
jobs:
  build: 
    name: Build mysql db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }} 
          username: sagarzemosolabs
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sagarzemosolabs/greencommute-db
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: database/
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/sagarzemosolabs/greencommute-db:latest
          labels: ${{ steps.meta.outputs.labels }}

