name: Build
on:
  workflow_dispatch:
jobs:
  build: 
    name: Build docker image 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          cd
          mkdir -p ~/.ssh
          echo "user ${USER_NAME}"
          echo "host ${HOSTNAME}"
          echo -e "$PRIVATE_KEY" > ~/.ssh/private_key && chmod 600 ~/.ssh/private_key
          cat ~/.ssh/private_key
          scp -i ~/.ssh/private_key docker-compose.yml ${USER_NAME}@${HOSTNAME}:.
