name: Bootcamp-monolithic

on:
  push:
    branches:
      - master

jobs:
  check_frontend_directory_changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.directory_changed.outputs.frontend_changed }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine if directory changed
        id: directory_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^frontend/'; then
            echo "Directory has changed"
            frontend_changed="true"
            echo "Output [$frontend_changed]"
            echo "frontend_changed=$frontend_changed" >> $GITHUB_OUTPUT
          else
            echo "Directory has not changed"
            frontend_changed="false"
            echo "Output [$frontend_changed]"
            echo "frontend_changed=$frontend_changed" >> $GITHUB_OUTPUT
          fi

  frontend_build:
    needs: check_frontend_directory_changes
    runs-on: ubuntu-latest
    if: ${{ needs.check_frontend_directory_changes.outputs.frontend_changed == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          echo "Building frontend"
          echo ${{ needs.check_frontend_directory_changes.outputs.frontend_changed }}

  check_backend_directory_changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.directory_changed.outputs.backend_changed }}
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine if directory changed
        id: directory_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^backend/'; then
            echo "Directory has changed"
            backend_changed="true"
            echo "Output [$backend_changed]"
            echo "backend_changed=$backend_changed" >> $GITHUB_OUTPUT
          else
            echo "Directory has not changed"
            backend_changed="false"
            echo "Output [$backend_changed]"
            echo "frontend_changed=$backend_changed" >> $GITHUB_OUTPUT
          fi

  backend_build:
    needs: check_backend_directory_changes
    runs-on: ubuntu-latest
    if: ${{ needs.check_backend_directory_changes.outputs.backend_changed == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          echo "Building backend"

  deploy:
    needs:  [ frontend_build,  backend_build]
    if: ${{ needs.check_backend_directory_changes.outputs.backend_changed == 'true' ||  needs.check_frontend_directory_changes.outputs.frontend_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          echo "Deploying"

