name: Bootcamp-monolithic

on:
  push:
    branches:
      - master

jobs:
  check_frontend_directory_changes:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine if directory changed
        id: directory_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^frontend/'; then
            echo "Directory has changed"
            echo "::set-output name=frontend_changed::true"
          else
            echo "Directory has not changed"
            echo "::set-output name=frontend_changed::false"
          fi

  frontend_build:
    needs: check_frontend_directory_changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          echo "Building frontend"
          echo ${{ needs.check_frontend_directory_changes.outputs.frontend_changed }}

  check_backend_directory_changes:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine if directory changed
        id: directory_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^backend/'; then
            echo "Directory has changed"
            echo "::set-output name=backend_changed::true"
          else
            echo "Directory has not changed"
            echo "::set-output name=backend_changed::false"
          fi

  backend_build:
    needs: check_backend_directory_changes
    runs-on: ubuntu-latest
    if: ${{ needs.check_backend_directory_changes.outputs.backend_changed == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the build
        run: |
          echo "Building backend"
